### PR TITLE
(remaining error) With true Andoer Color Checker 24

### PR DESCRIPTION
**Pull request by j2l**
As I have a Andoer Color Checker (the cheapo one), I also wanted to share something useful.

So, I added the 24 colors, converted from backpanel RGB (255,255,255) to hex to Blender RGB (1,1,1) in Blender to add them into the script. 
I also added  my shot of the colorchecker with a Canon 7D and snapshots to help understand the process and have a kind of reference shot. Added my name in authors, hope it's fine :)

I noticed that simply unregistering and removing the add-on, then re-install it isn't enough to purge data from Blender.
I needed to re-start Blender after each trial.

I end up with an error though:
```
Python: Traceback (most recent call last):
  File "/home/user/.config/blender/2.91/scripts/addons/blender_colorchecker/NODE_OT_ColorCheckerMatch.py", line 96, in execute
    hh_points[index].location = (hue_x, hue_y(hue_x, h))
IndexError: bpy_prop_collection[index]: index 9 out of range, size 9
location: <unknown location>:-1
```
I can't find an index size of 9, AFAIK, I changed all I found to match the 24 entries. Please have a diff check and let me know to modify it before merging.

### CODE REVIEW

**Comment by semagnum** [comment]
Thank you for taking the time to update this! Glad to have someone that's worked closely with color checkers. With all the projects I've started up, I have my hands full.
I think what is happening is that although your colorchecker_h should have 25 (you can do an `assert` to make sure), the hue node may have less than that. My current implementation removes excess points, but I don't think it adds any. So before that enumerated for loop, just add a loop to add additional points if necessary (or have the enumerated loop check it).

**Comment by semagnum** [comment]
Once you're done, this will be great to merge. Ideally, in a future project, we could find a way to abstract this more, and users could add presets for different kinds of color checkers.

**Comment by semagnum** [comment]
After looking at it longer, this is going to take more than just a fix:
- The arithmetic for the hues needs to be adjusted - since some of these colors aren't pure saturations, they don't sit on the flat Hue Correct line by default (so by default, they're still changing the image, which it shouldn't)
- You added the black-to-white colors into the hue correction node. Not only would this not be correct, but it'd need to be in a separate node, probably RGB curves.
- For the sake of user experience and coding standard, I'd rather have the colors actually given their true names as variables and in the UI panel, instead of just 00-24. And abstracting this out into a collection where colors could be added/removed would be best.

**Comment by j2l** [comment]
Hello,
I don't know how to do this. Way beyond my knowledge.

**Comment by semagnum** [comment]
Okay, thanks for letting me know. I am going to close this pull request since this commit is unfinished and not up to standards. However, I will add an issue with a link to your fork so others can see what you started to implement. I unfortunately don't have time to spend due to other priorities, but I'll post the information so someone else can :)

**Comment by j2l** [comment]
OK. So sad, seems buried for at least another year.

**Comment by semagnum** [comment]
Not necessarily. Since I published this for free, it's low on my priority list (hence the public repo so others can work on it). In the meantime, you could post about this on BlenderArtists or elsewhere and see if other developers would like to help with us.
Until then, I'm gonna lock this PR.

**Pull request closed without merging**
